#!/usr/bin/env python3
"""
TikTok Video Upload Script (Playwright Mode)
Загрузка видео на TikTok через browser automation с cookies

Usage:
    python3 upload_tiktok_playwright.py video.mp4 "Caption!" #foryou #viral
"""

import sys
import argparse
from pathlib import Path
from src.tiktok_bot import TikTokBotUploader

def parse_args():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(
        description='Upload video to TikTok using Playwright automation'
    )

    parser.add_argument('video', type=str, help='Path to video file (MP4)')
    parser.add_argument('caption', type=str, nargs='?', help='Video caption')
    parser.add_argument('--hashtags', type=str, nargs='*', help='Hashtags (without #)')
    parser.add_argument('--privacy', type=str, default='public',
                       choices=['public', 'friends', 'private'],
                       help='Privacy level (default: public)')
    parser.add_argument('--test', action='store_true',
                       help='Test cookies connection without upload')

    return parser.parse_args()

def main():
    """Main upload function"""

    args = parse_args()

    print("=" * 70)
    print("🎵 TIKTOK VIDEO UPLOAD (PLAYWRIGHT)")
    print("=" * 70)
    print()

    video_path = Path(args.video)

    if not video_path.exists():
        print(f"❌ Video file not found: {video_path}")
        return False

    # Test mode
    if args.test:
        print("🧪 Testing cookies connection...")
        print()
        try:
            uploader = TikTokBotUploader()
            uploader.init_browser(headless=True)

            print("✅ Cookies loaded successfully!")
            print("✅ Playwright browser initialized!")
            print()
            print("✨ TikTok connection is ready for upload!")
            print()
            print("📊 Cookies location:", uploader.config.get('cookies_path'))
            print()
            return True

        except Exception as e:
            print(f"❌ Connection test failed: {e}")
            return False

    # Prepare caption
    caption = args.caption or f"Generated by AI {video_path.stem}"

    # Add hashtags if provided
    if args.hashtags:
        hashtags_str = ' '.join(f'#{tag}' for tag in args.hashtags)
        caption = f"{caption}\n\n{hashtags_str}"

    # Display upload info
    print("📹 Video:", video_path)
    print("📏 Size: {:.2f} MB".format(video_path.stat().st_size / (1024 * 1024)))
    print("📝 Caption:", caption[:50] + "..." if len(caption) > 50 else caption)
    print("🔒 Privacy:", args.privacy)
    print()
    print("=" * 70)
    print()
    print("🚀 Starting upload to TikTok...")
    print()

    try:
        # Initialize uploader
        uploader = TikTokBotUploader()

        # Upload video
        result = uploader.upload_video(
            video_path=video_path,
            caption=caption,
            privacy=args.privacy
        )

        if result['success']:
            print()
            print("=" * 70)
            print("✅ UPLOAD COMPLETE!")
            print("=" * 70)
            print()
            print(f"🆔 Video ID: {result.get('video_id', 'N/A')}")
            print(f"🔗 URL: {result.get('url', 'N/A')}")
            print()
            print("✨ TikTok uploaded successfully!")
            print("=" * 70)
            return True
        else:
            print()
            print("=" * 70)
            print("❌ UPLOAD FAILED")
            print("=" * 70)
            print()
            print(f"🔴 Error: {result.get('error', 'Unknown error')}")
            print()
            return False

    except Exception as e:
        print()
        print("=" * 70)
        print("❌ UPLOAD ERROR")
        print("=" * 70)
        print()
        print(f"🔴 Error: {e}")
        print()
        import traceback
        traceback.print_exc()
        print()
        print("💡 Troubleshooting:")
        print("   • Check if cookies are valid (import using import_tiktok_cookies.py)")
        print("   • Test connection: python3 upload_tiktok_playwright.py --test")
        print("   • Ensure TikTok account is not banned")
        print("=" * 70)
        return False


if __name__ == '__main__':
    success = main()
    sys.exit(0 if success else 1)
