#!/usr/bin/env python3
"""
TikTok Video Upload Script
Upload video to TikTok using official API

Usage:
    python3 upload_to_tiktok.py /path/to/video.mp4 "Video caption" #hashtag1 #hashtag2

Example:
    python3 upload_to_tiktok.py shorts/TikTok_Video.mp4 "Cool video! #foryou #viral"
"""

import json
import sys
import os
from pathlib import Path
from src.tiktok_api import TikTokAPIUploader

def parse_hashtags(args):
    """Extract hashtags from args"""
    hashtags = []
    for arg in args:
        if arg.startswith('#'):
            hashtags.append(arg[1:])
    return hashtags

def parse_caption_caption(args):
    """Extract caption from args (non-hashtag text)"""
    caption = ''
    for arg in args:
        if not arg.startswith('#'):
            caption += arg + ' '
    return caption.strip()

def main():
    if len(sys.argv) < 2:
        print("""
🎵 TikTok Video Upload Script
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Usage:
    python3 upload_to_tiktok.py <video_path> [caption] [hashtags]

Example:
    python3 upload_to_tiktok.py video.mp4 "My awesome video!" #foryou #viral

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""")
        sys.exit(1)

    video_path = Path(sys.argv[1])

    # Parse caption and hashtags from remaining args
    caption_text = parse_caption_caption(sys.argv[2:])
    hashtags = parse_hashtags(sys.argv:])

    # If no caption provided, ask for it
    if not caption_text:
        print("📝 Please provide video caption (or press Enter to use default):")
        caption_text = input("> ").strip()

        if not caption_text:
            timestamp = Path(video_path).stem
            caption_text = f"Generated by Video Publisher Bot {timestamp}"

    print()
    print("=" * 70)
    print("🎵 TIKTOK VIDEO UPLOAD")
    print("=" * 70)
    print()
    print(f"📹 Video: {video_path}")
    print(f"📝 Caption: {caption_text[:50]}...")
    if hashtags:
        print(f"#️⃣ Hashtags: {', '.join(hashtags)}")
    print()
    print("=" * 70)
    print()
    print("🚀 Starting upload to TikTok...")
    print()

    try:
        uploader = TikTokAPIUploader()

        result = uploader.upload_and_publish(
            video_path=video_path,
            caption=caption_text,
            privacy_level='public_to_everyone',
            hashtags=hashtags if hashtags else None
        )

        print()
        print("✅ UPLOAD COMPLETE!")
        print(f"🆔 Video ID: {result.get('video_id')}")
        print(f"🔗 URL: {result.get('url')}")
        print()

        # Save result to log
        log_file = Path(__file__).parent.parent / 'logs' / 'upload_history.json'
        log_file.parent.mkdir(exist_ok=True)

        logs = []
        if log_file.exists():
            with open(log_file, 'r') as f:
                try:
                    logs = json.load(f)
                except:
                    logs = []

        logs.append({
            'timestamp': Path(video_path).stem,
            'video_id': result.get('video_id'),
            'url': result.get('url'),
            'caption': caption_text[:100],
            'hashtag_count': len(hashtags),
            'uploaded_at': None  # Would be datetime.now() but avoid module import issues
        })

        with open(log_file, 'w') as f:
            json.dump(logs, f, indent=2)

        print(f"📝 Upload logged to: {log_file}")
        print()

    except Exception as e:
        print()
        print("=" * 70)
        print("❌ UPLOAD FAILED")
        print("=" * 70)
        print(f"🔴 Error: {e}")
        print()
        import traceback
        traceback.print_exc()
        print()
        print("💡 Troubleshooting:")
        print("   • Check API credentials in config/api_credentials.json")
        print("   • Run: python3 test_tiktok_api.py")
        print("   • Ensure access token is valid (24h in test mode)")
        print("=" * 70)
        sys.exit(1)


if __name__ == '__main__':
    main()
